import { callLLM } from './llm.js';
import { getSystemPrompt } from './prompt.js';
import { getToolsDetails, executeTool } from '../tools/registry.js';
import OpenAI from 'openai';
import { repository } from '../memory/repository.js';

const MAX_ITERATIONS = 5;

export const processUserMessage = async (userId: number, text: string): Promise<string> => {
  await repository.saveMessage({
    user_id: userId,
    role: 'user',
    content: text
  });

  const history = await repository.getMessages(userId);
  
  const messages: OpenAI.Chat.Completions.ChatCompletionMessageParam[] = [
    { role: 'system', content: getSystemPrompt() },
    ...history.map(msg => {
      if (msg.role === 'tool') {
        return {
          role: 'tool',
          content: msg.content ?? "",
          tool_call_id: msg.tool_calls!
        } as OpenAI.Chat.Completions.ChatCompletionToolMessageParam;
      }
      if (msg.role === 'assistant' && msg.tool_calls) {
        return {
          role: 'assistant',
          content: msg.content,
          tool_calls: JSON.parse(msg.tool_calls)
        } as OpenAI.Chat.Completions.ChatCompletionAssistantMessageParam;
      }
      return {
        role: msg.role as 'user' | 'assistant',
        content: msg.content ?? ""
      } as OpenAI.Chat.Completions.ChatCompletionMessageParam;
    })
  ];

  let iterations = 0;
  
  while (iterations < MAX_ITERATIONS) {
    iterations++;
    
    // Pass tools if any exist
    const tools = getToolsDetails();
    const responseMessage = await callLLM(messages, tools);
    
    if (responseMessage.tool_calls && responseMessage.tool_calls.length > 0) {
      messages.push(responseMessage);
      await repository.saveMessage({
        user_id: userId,
        role: 'assistant',
        content: responseMessage.content,
        tool_calls: JSON.stringify(responseMessage.tool_calls)
      });
      
      for (const toolCall of responseMessage.tool_calls) {
        const result = await executeTool(toolCall.function.name, toolCall.function.arguments);
        
        const toolMsg: OpenAI.Chat.Completions.ChatCompletionToolMessageParam = {
          role: 'tool',
          tool_call_id: toolCall.id,
          content: result
        };
        messages.push(toolMsg);
        
        await repository.saveMessage({
          user_id: userId,
          role: 'tool',
          content: result,
          tool_calls: toolCall.id
        });
      }
    } else if (responseMessage.content) {
      await repository.saveMessage({
        user_id: userId,
        role: 'assistant',
        content: responseMessage.content
      });
      return responseMessage.content;
    } else {
       return "No response generated by the model.";
    }
  }
  
  return "Error: Agent reached maximum iterations without completing the task.";
};
